---
title: "Project 1"
author: "Shayne Cassidy (sc5za) Sarah Winston Nathan (swn2bf) Sarah Nelson (skn5mq)"
date: "10/20/2019"
output: html_notebook
---

## Part 1: Generating Hypotheses

Based on the analysis conducted in part 1b, I have been able to form some well-informed hypotheses from the visualizations. They are as follows, listed as null and alternative hypotheses and followed by how I arrived at them:

..As for accident severity in regards to **Accident Damage (ACCDMG)**:
*1) H0: Higher train speeds among freight trains have no effect on accident damage*
*Ha: Higher train speeds among freight trains result in higher accident damage*

*2) H0: Accidents caused by Human Factors have no effect on accident damage*
*Ha Accidents caused by Human Factors have an effect on accident damage*

..As for accident severity in regards to **Casualties**: 

*1) H0: Derailment caused accidents do not increase the number of casualties*  
*Ha: Derailment caused accidents do increase the number of casualties* 

*2) H0: Highway-rail crossing accidents are more severe than other types of accidents*
*Ha: Highway-rail crossing accidents are not more severe than other types of accidents*

## Part 2: ACCDMG Analysis

*Hypothesis 1*

Fill in here steps a-e
(a) The feature and model selection techniques you used to find appropriate models for this problem;
(b) Your treatment of ordinal and categorical variables (i.e., how were
they coded);
(c) How you assessed your models (e.g., adjusted R2, AIC, etc.);
(d) How you diagnosed problems with the models; and
(e) How you adjusted the models based on these assessments.


*Hypothesis 2*

Fill in here steps a-e
(a) The feature and model selection techniques you used to find appropriate models for this problem;
(b) Your treatment of ordinal and categorical variables (i.e., how were
they coded);
(c) How you assessed your models (e.g., adjusted R2, AIC, etc.);
(d) How you diagnosed problems with the models; and
(e) How you adjusted the models based on these assessments.


## Part 3: Casualties

*Hypothesis 1*

Fill in here steps a-e
(a) The feature and model selection techniques you used to find appropriate models for this problem;
(b) Your treatment of ordinal and categorical variables (i.e., how were
they coded);
(c) How you assessed your models (e.g., adjusted R2, AIC, etc.);
(d) How you diagnosed problems with the models; and
(e) How you adjusted the models based on these assessments.


*Hypothesis 2* 

Fill in here steps a-e
(a) The feature and model selection techniques you used to find appropriate models for this problem;
(b) Your treatment of ordinal and categorical variables (i.e., how were
they coded);
(c) How you assessed your models (e.g., adjusted R2, AIC, etc.);
(d) How you diagnosed problems with the models; and
(e) How you adjusted the models based on these assessments.


## Part 4: Evidence and Recommendations to FRA

### Part a)

### Part b)